image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "26"
  ANDROID_BUILD_TOOLS: "27.0.1"
  ANDROID_SDK_TOOLS_REV: "4333796"  # "26.1.1"

before_script:
  - mkdir $HOME/.android # For sdkmanager configs
  - echo 'count=0' > $HOME/.android/repositories.cfg # Avoid warning
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS_REV}.zip
  - mkdir $PWD/android-sdk-linux
  - unzip -qq android-sdk.zip -d $PWD/android-sdk-linux
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$ANDROID_HOME/platform-tools/
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager --update > /dev/null 2>&1
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'tools' > /dev/null 2>&1
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'platform-tools' > /dev/null 2>&1
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'build-tools;'$ANDROID_BUILD_TOOLS > /dev/null 2>&1
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'platforms;android-'$ANDROID_COMPILE_SDK > /dev/null 2>&1
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'extras;android;m2repository' > /dev/null 2>&1
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'extras;google;google_play_services' > /dev/null 2>&1
  - echo y | $ANDROID_HOME/tools/bin/sdkmanager 'extras;google;m2repository' > /dev/null 2>&1
  - (echo y; echo y; echo y; echo y; echo y; echo y) | $ANDROID_HOME/tools/bin/sdkmanager --licenses
  - chmod +x ./gradlew

stages:
  - build

build:
  stage: build
  script:
    - ./gradlew assembleDebug --stacktrace
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_TAG}_${CI_COMMIT_SHA}"
    paths:
    - app/build/outputs/
